### ISSUE TITLE
Weird scaling issue on Reddit recommendation

### ISSUE THREAD

**Issue by MattGrimes** [raymak/contextualfeaturerecommender#224]
Just got the recommendation for the enhanced Reddit addon. It had a weird scaling issue where I had to scroll around in the box to see what the recommendation actually was. I've seen it before when I first start firefox as well. 

![reddit](https://cloud.githubusercontent.com/assets/6538151/11289004/66c43f6a-8edd-11e5-8a27-1b1d6341f24c.png)

**Comment by gregglind** [comment]
Claim: this is a doorhanger bug, under unknown circumstances.
