### ISSUE TITLE
Recommends incompatible extension

### ISSUE THREAD

**Issue by hwine** [raymak/contextualfeaturerecommender#252]
I'm currently using the Tab Center Test Pilot extension. CFR recommended "Tree Style Tab" extension, which is either redundant or incompatible. It would be great if there was some notion of "compatibility" or a "softer sell" if a lot of extensions are already installed. (E.g. "this might help your workflow" as additional verbiage.)
Tough problem - I don't have any real suggestions. Just felt "odd" as my first recommendation.

**Comment by raymak** [comment]
Thanks for the feedback. It is definitely a problem that will be addressed in the next versions. We have already thought about it and have some ideas on how to solve it. For example, we will have rules that say don't recommend Tree Style Tab if the user already has a similar addon.

**Comment by raymak** [comment]
Temporary workaround added: https://github.com/raymak/contextualfeaturerecommender/blob/master/phase2/addon/lib/controller.js#L844-L854
