### ISSUE TITLE
I was recommended the Tree Style Tab add-on even though I have Tab Center test pilot

### ISSUE THREAD

**Issue by armenzg** [raymak/contextualfeaturerecommender#253]
I was recommended:
https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/?src=fr-dh

but I'm already using Tab Center from Test Pilot which is equivalent.

If you have Tab Center users jump into recommender they will be confused.
We're talking about hudreds? thousands? of Tab Center users.

**Comment by raymak** [comment]
related to #252

**Comment by gregglind** [comment]
dup of #252 

@armenzg  Thanks for reporting!
