### ISSUE TITLE
the ui looks... old, and xul-ish.  reskin?

### ISSUE THREAD

**Issue by gregglind** [raymak/contextualfeaturerecommender#258]

**Comment by raymak** [comment]
yeah, I agree. It looks 2014 firefox-tour-ish.

**Comment by designakt** [comment]
we will provide you with a mock of how it could look.
In the meantime: there is a WIP Styleguide with how panels should look. (including code snippets)
https://firefoxux.github.io/StyleGuide/#/components/panels

**Comment by gregglind** [comment]
<img width="384" alt="screen shot 2016-07-20 at 9 18 12 am" src="https://cloud.githubusercontent.com/assets/163983/16989754/fde9d6f6-4e5a-11e6-888e-687712658e69.png">

That is: 
- lit button
- 'top area' (I don't like it) open
- fx icon showing
- 'x' to close.
- "reason" showing.  Reason seems to be important for uptake. 

Intended elements:
- data collection of 'not this', 'not now', 'this is awesome'
- closeable
- re-callable
- reason for rec

**Comment by gregglind** [comment]
https://people.mozilla.com/~glind/all/featurerecommender@insights.mozilla.com-0.0.60-beta.xpi

**Comment by raymak** [comment]
It's better if the changes are not too dramatic.

**Comment by designakt** [comment]
The first round will only be a re-skin using new Firefox UI standards.

**Comment by tsteuer** [comment]
## Redesign - Mockup

Hey guys, here's my Mockup of the Redesign so far. Try it out and let me know what you think. You can leave comments inside the Mockup on certain spots if you like. Some elements had to be changed or left out to match the new Firefox UI Standards, that is why this concept goes beyond a simple reskin.

[![Mockup_Redesign](https://cloud.githubusercontent.com/assets/18701233/17154040/a6bb1424-537f-11e6-8136-22bebab9794a.png)](https://invis.io/6V82YZFK7)

**Comment by tsteuer** [comment]
Hey Guys, here are the two missing icons...they are saved as PNG, SVG and native Adobe Illustrator file.
[Icon_Toolbar.zip](https://github.com/raymak/contextualfeaturerecommender/files/386854/Icon_Toolbar.zip)
[Icon_Shortcut.zip](https://github.com/raymak/contextualfeaturerecommender/files/386855/Icon_Shortcut.zip)

**Comment by gregglind** [comment]
http://f.cl.ly/items/0k143r3B0p0J2c2r360Q/glyph-keyboard-16.svg
