### ISSUE TITLE
shield-utils and CFR interactions

### ISSUE THREAD

**Issue by raymak** [raymak/contextualfeaturerecommender#271]

**Comment by raymak** [comment]
post-study survey -> util
clean up -> function in CFR, called by util
logging -> CFR

**Comment by raymak** [comment]
shield uses prefs: "variation" and "firstrun"

**Comment by gregglind** [comment]
these are the only interesting prefs.

**Comment by raymak** [comment]
disable survey -> util

**Comment by gregglind** [comment]
This is complete.

**Comment by gregglind** [comment]
[shorlander keyboard icon](http://f.cl.ly/items/0k143r3B0p0J2c2r360Q/glyph-keyboard-16.svg)
